public enum Permiso {
    CREAR_SUCURSAL,
    VER_SUCURSALES,
    CREAR_CLIENTE,
    CREAR_CUENTA,
    VER_CLIENTES,
    VER_CUENTAS,
    VER_TRANSACCIONES,
    DEPOSITAR_PROPIO,
    EXTRAER_PROPIO,
    TRANSFERIR_PROPIO
}